### ISSUE TITLE
体验优化-第一次运行

### ISSUE THREAD

**Issue by Sokwva** [orzogc/acfunlive#11]
第一次运行时[参数为-web -listen]，会提示没有配置文件
    “[ERROR] 请订阅指定主播的开播提醒或自动下载，运行 acfunlive -h 查看帮助”，
但是我认为，程序应该直接在后台运行，等待后续的命令或者助手插件发过来的请求；而不是还需要使用命令添加一个用户才能使用后续的功能。

**Comment by orzogc** [comment]
最近没空整，要等一下

**Comment by Sokwva** [comment]
不急
