### ISSUE TITLE
有时候开播过了几分钟才开始录制

### ISSUE THREAD

**Issue by umitanoshii** [orzogc/acfunlive#13]
有的主播开播后过了一段时间(大概有2-5分钟)才会开始录制，acfunlive在这段时间内使用getdlurl {房间号}，也会显示不在直播
同时发现主播开播后过一段时间才会出现在acfun的直播页面上，观察到acfunlive也是在差不多的时间点提示主播开播并录制，不知道其中有没有关联？

**Comment by orzogc** [comment]
这应该是A站API的bug（或者特性？），只有直播分区里的虚拟偶像区的才会这样，向猴子反映过，猴子没有回复。

**Comment by umitanoshii** [comment]
> 
> 
> 这应该是A站API的bug（或者特性？），只有直播分区里的虚拟偶像区的才会这样，向猴子反映过，猴子没有回复。

感谢解答，录播开头少了几分钟还是会感到可惜
看到issue#1 #1 用a站这个api前有其他方法，能否考虑下让acfunlive支持切换检测直播状态方式呢？
