### ISSUE TITLE
录像突然频繁出现无法获取直播源的问题

### ISSUE THREAD

**Issue by nochiyan** [orzogc/acfunlive#15]
![QQ截图20200808203109](https://user-images.githubusercontent.com/25357477/89710566-ee174880-d9b6-11ea-9079-960633f7e2e1.jpg)
8月7日开始突然频繁出现的问题，一般再手动录像时就能正常进行录制，手动获取直播流也没问题

**Comment by orzogc** [comment]
好像是A站自己的bug，最新的代码已经修复

**Comment by nochiyan** [comment]
> 好像是A站自己的bug，最新的代码已经修复，等下我发布一个新的release

好的~辛苦了

**Comment by orzogc** [comment]
你现在试试0.4版本
可能偶尔还会无法获取直播源，这时要你自己手动下载

**Comment by nochiyan** [comment]
> 你现在试试0.4版本
> 可能偶尔还会无法获取直播源，这时要你自己手动下载

好的！
