### ISSUE TITLE
0.4版本的问题

### ISSUE THREAD

**Issue by nochiyan** [orzogc/acfunlive#16]
![QQ截图20200809000722](https://user-images.githubusercontent.com/25357477/89715055-8ae8de80-d9d5-11ea-84f3-f64a799c806c.jpg)
即使关闭webapi输出也不能在命令行窗口显示内容，而且会疯狂占用CPU及内存，打开webapi查看日志发现后台一直在报错刷屏，如图

**Comment by orzogc** [comment]
应该是打印日志的问题

**Comment by orzogc** [comment]
你再重新下载0.4版本试一下

**Comment by nochiyan** [comment]
> 你再重新下载0.4版本试一下，使用命令行模式需要`-nogui`参数，直接双击运行应该是会有系统托盘的，麻烦都测试一下

占用正常了 但是不论怎样都还是无法进入命令行模式

**Comment by orzogc** [comment]
麻烦下载0.4的cli版本试试命令行模式
另外gui版本能正常使用吗？

**Comment by nochiyan** [comment]
ok 两个版本现在都能正常使用了
