### ISSUE TITLE
无法获取直播源

### ISSUE THREAD

**Issue by AgKey47** [orzogc/acfunlive#17]
https://i.loli.net/2020/08/10/X7TC46x2kNPMEyo.png
https://i.loli.net/2020/08/10/UBl26snwjgXx1po.png
0.4和0.3.3版本均无法自动或手动获取直播源

**Comment by orzogc** [comment]
我也不知道原因，看网页API应该没改，可能是反爬导致的

**Comment by orzogc** [comment]
你试试0.4.1版本

**Comment by AgKey47** [comment]
> 你试试0.4.1版本

可以了

**Comment by orzogc** [comment]
这问题应该彻底修复了，你应该用0.4.2版本
