### ISSUE TITLE
与浏览器插件整合

### ISSUE THREAD

**Issue by Sokwva** [orzogc/acfunlive#2]
可以通过浏览器插件，在直播页面加上一个按钮，这个按钮点击后可以直接发送录制的请求给此程序。
同时，订阅开播提醒也可以在个人中心上面添加一个按钮，将uid的值传递给程序。
请问有没有搞头😗

**Comment by orzogc** [comment]
怎么搞？

**Comment by Sokwva** [comment]
本地监听一个端口，插件前台直接通过HTTP协议发送请求。

**Comment by btjoker** [comment]
油猴挺简单的, 直播页面的要设置延迟运行脚本
集成个web服务, 网页通过按钮点击, fetch发送uid到本地, 根据path决定是加入提醒还是下载

**Comment by orzogc** [comment]
我研究一下吧，应该就是通过访问`http://localhost:port/命令/uid`来发送请求

**Comment by Sokwva** [comment]
对的，我那时候还特地看了插件调用本地程序；对比那种，还是这种监听TCP端口的办法好多了。

**Comment by orzogc** [comment]
弄出来了，你们测试看看有没有问题

**Comment by Sokwva** [comment]
好

**Comment by Sokwva** [comment]
> 弄出来了，你们测试看看有没有问题

你好，服务器返回可以采用json之类的格式吗

**Comment by Sokwva** [comment]
我们还需要的返回有
1.关注的所有主播的列表
2.正在录制的主播的列表

**Comment by orzogc** [comment]
> 我们还需要的返回有
> 1.关注的所有主播的列表
> 2.正在录制的主播的列表

第二个已经有了

**Comment by orzogc** [comment]
好了，你再测试

**Comment by Sokwva** [comment]
> 好了，你再测试

辛苦了

**Comment by Sokwva** [comment]
Need to Handle CORS Requests
https://github.com/gorilla/mux#handling-cors-requests
本地访问需要解决跨域问题（在服务器端头部加入允许跨域的头部）

**Comment by orzogc** [comment]
你现在再试试

**Comment by Sokwva** [comment]
可以了，整合完成，谢谢
