### ISSUE TITLE
群晖DSM可以运行吗

### ISSUE THREAD

**Issue by RcYYYang** [orzogc/acfunlive#21]
群晖DSM下没有yum和apg-get，只有ipkg，几个依赖的包全都没有。
不知道还有没有别的办法可以不用虚拟机直接在DSM上运行acfunlive呢。

**Comment by orzogc** [comment]
不录播的话没有运行依赖，录播的话需要FFmpeg

**Comment by RcYYYang** [comment]
主要是几个编译的依赖都没有，不知道该怎么编译安装。
直接./acfunlive显示缺少libappindicator3库，但是ipkg中并没有这个库。

**Comment by orzogc** [comment]
加上参数`-nogui`运行试试

**Comment by RcYYYang** [comment]
./acfunlive: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory
好像还是不可以，可能还是得上虚拟机。

**Comment by orzogc** [comment]
你可以自己下载libappindicator的源码自己编译gtk3版本
https://launchpad.net/libappindicator
参考Arch Linux的编译方法：
https://github.com/archlinux/svntogit-community/blob/packages/libappindicator/trunk/PKGBUILD

**Comment by orzogc** [comment]
还有你那个群晖DSM是什么系统的？啥都没有？

**Comment by orzogc** [comment]
我还是打包个静态编译的给你吧

**Comment by RcYYYang** [comment]
对确实就是什么都没有，就是群晖自带的那个系统，我也不知道属于哪个分支的linux。
群晖上显示的是DSM 6.2.3

**Comment by RcYYYang** [comment]
ipkg包少的不行，git还是1.8.x版本号。wget还不支持https，折腾一晚上什么都没弄出来 : (

**Comment by RcYYYang** [comment]
大佬不用帮我编译了，我虚拟个centos就行了，不搞这些奇奇怪怪的事情了。

**Comment by RcYYYang** [comment]
大佬我又来了，折腾了好久弄了个CentOS还是没搞定。。
编译需要的话连不上golong要翻墙，直接运行release的linux版本显示权限不够。搞不懂为什么，明明也是sudo -i的root权限。
大佬有空的话可不可以帮我打包一个静态编译的呢，我试试群晖dsm上可不可以用。刚发现ipkg的包里面竟然有ffmpeg。

**Comment by orzogc** [comment]
用了cgo，没办法静态链接，你得自己编译
连接不上就用goproxy，比如 https://goproxy.cn/ 或 https://mirrors.aliyun.com/goproxy/

**Comment by RcYYYang** [comment]
好的我自己再研究研究，谢谢。
