### ISSUE TITLE
windows版占用突然出现异常

### ISSUE THREAD

**Issue by nochiyan** [orzogc/acfunlive#22]
大概从11号凌晨开始，只要使用mirai的功能就会出现CPU和内存爆炸的问题，之前用的0.4.5版本，尝试更换0.4.6、系统版本、QQ号、命令行/webui版本等方法还是有这个问题，占用满之后就无限获取直播间信息失败，没有占用满则不会，不使用mirai提醒则没有问题。

**Comment by orzogc** [comment]
那个时候你是不是用机器人QQ加了某个很活跃的QQ群，或者以前加的某个QQ群变得很活跃？

**Comment by nochiyan** [comment]
> 那个时候你是不是用机器人QQ加了某个很活跃的QQ群，或者以前加的某个QQ群变得很活跃？

没有 只有一个群 换过没有群的QQ空号也是这样的

**Comment by orzogc** [comment]
你用一下0.4.6.1版本试试

**Comment by nochiyan** [comment]
> 你用一下0.4.6.1版本试试

好，现在正常了！
