### ISSUE TITLE
运行后错误，无法初始化服务器

### ISSUE THREAD

**Issue by RcYYYang** [orzogc/acfunlive#23]
Unable to init server: Could not connect: Connection refused

(acfunlive:2520): Gtk-WARNING **: 17:49:14.294: cannot open display:

docker ubuntu18.04

**Comment by orzogc** [comment]
不支持docker吧，加上参数`-nogui -listen`运行试试

**Comment by orzogc** [comment]
所以docker能运行了吗？

**Comment by RcYYYang** [comment]
可以，用-nogui -listen参数，docker ubuntu18.04完美运行。
有一个小bug就是录制出来的文件名中带时间，其中时间有冒号“:”，但是冒号在win系统中不可以用作文件名。
所以在linux中看是正常，但是传到win中就是乱码，希望可以改一下这个命名规则。

**Comment by orzogc** [comment]
这个你自己写个脚本改
