### ISSUE TITLE
关于mirai的QQ群通知

### ISSUE THREAD

**Issue by bitest** [orzogc/acfunlive#25]
我测试了三种情况，机器人分别是：
普通群员；
管理员；
群主。
其中只有群主能成功发出开播通知，但是在log中三个群都有记录：
“给QQ群 xxxxxxxx 发送消息”

请问这个有解决方案吗？

**Comment by bitest** [comment]
重新测试了一下，之前控制变量没做好。普通群员绝对发送不成功，管理员和群主好像是同一级的，但是在同一个直播间的配置里只能成功发送一个。

**Comment by orzogc** [comment]
现在应该修复了，注意@全体成员 是有次数限制的，超过限制后会发不了消息
