### ISSUE TITLE
Linux系统下跨磁盘移动文件的问题

### ISSUE THREAD

**Issue by bitest** [orzogc/acfunlive#26]
os.Rename对跨磁盘的操作无效，导致下载目录设置在rclone挂载的GDrive上没法用。

我不会编程，但是我在网上偷了段代码一边试错一边瞎改，土法炼钢居然跑成功了…大概是这么个样子：

			inputFile, err := os.Open(oldFile)
			defer inputFile.Close()
			outputFile, err := os.Create(newFile)
			defer outputFile.Close()
			_, err = io.Copy(outputFile, inputFile)
			err = os.Remove(oldFile)

希望大佬能搞个正规的，不然我的玩具VPS顶不住…

**Comment by orzogc** [comment]
这代码没什么问题，加上错误处理就好了

**Comment by bitest** [comment]
我发现还是有问题，这段代码虽然让我在Linux下可以正常复制文件到远程目录并删除源文件，但是在Windows上就变成删不掉源文件了。
报错我只看得懂是源文件被占用了，但是我一个门外汉没办法解决了。:(

[ERROR] Recovering from panic in recordLive(), the error is: remove D:\Program Files\acfunlive\XXX.mp4: The process cannot access the file because it is being used by another process.

**Comment by orzogc** [comment]
大概这样
```go
inputFile, err := os.Open(oldFile)
checkErr(err)
defer inputFile.Close()
outputFile, err := os.Create(newFile)
checkErr(err)
defer outputFile.Close()
_, err = io.Copy(outputFile, inputFile)
checkErr(err)
inputFile.Close()
err = os.Remove(oldFile)
checkErr(err)
```

**Comment by bitest** [comment]
inputFile.Close()我在上一次回复之前就试过了，连你建议加入的checkErr(err)位置都和你的代码是一模一样的，但是在我的Windows电脑上运行一直是这个结果，不知道为什么。
