### ISSUE TITLE
请问下linux系统上如何开机自动运行呢？

### ISSUE THREAD

**Issue by shaochen206** [orzogc/acfunlive#28]
我试了下crontab和/etc/rc.local中设置开机直接运行/dir/acfunlive -listen或者nohup和&运行在后台，写在sh文件中开机执行sh文件也都没法在打开主机的时候自动监听，请问有什么办法可以在开机后自动运行不用登陆进去手动执行程序吗？

**Comment by orzogc** [comment]
用systemd试试

**Comment by shaochen206** [comment]
> 用systemd试试

感谢，用systemd可以了
