### ISSUE TITLE
适配Windows service

### ISSUE THREAD

**Issue by Sokwva** [orzogc/acfunlive#3]
建议将cli界面与核心的功能拆分出来，以便后期可以安装为windows的服务

**Comment by Sokwva** [comment]
因为考虑到普通用户一般不会使用命令行，所以我希望您能将它除了cli处理的其他部分能注册为Windows服务、或者是能直接双击然后在托盘运行的守护程序。

**Comment by orzogc** [comment]
任务栏托盘是可以，但是我基本不用windows，无法测试

**Comment by Sokwva** [comment]
那就托盘吧，注册成服务还麻烦一点

**Comment by orzogc** [comment]
GUI可能会用electron

**Comment by Sokwva** [comment]
> GUI可能会用electron

建议GUI版本和CLI版本都创建为单独分支

**Comment by hlytime** [comment]
我这样的应该不算普通用户，不知道如何配置config.json，使用说明也不知道如何下手( ﾟ∀。)

**Comment by wpscott** [comment]
托盘可以考虑[systray](https://github.com/getlantern/systray)，使用简单，跨平台
顺便可以考虑把定时器监控文件修改改成使用[fsnotify](https://github.com/fsnotify/fsnotify)，也是跨平台的。Windows睡眠被唤醒可能是定时器的问题

**Comment by orzogc** [comment]
写了个web ui： https://github.com/orzogc/acfunlive-ui
可以试用一下

**Comment by Sokwva** [comment]
> 写了个web ui： https://github.com/orzogc/acfunlive-ui
> 可以试用一下

可算出来了，我在助手上面写了个建议的交互页面，但是完整写下去功能又不完善，写又不是，不写又不是；现在终于可以把问题解决了，哈哈哈。

**Comment by orzogc** [comment]
现在直接运行会有系统托盘，麻烦试用一下

**Comment by Sokwva** [comment]
> 现在直接运行会有系统托盘，麻烦试用一下

嗯嗯，知道，我的想法是希望能做到双击就能直接隐藏到托盘后台工作的；而且托盘有时候会出现很多个图标的bug。
