### ISSUE TITLE
菜鸡一直卡在编译报错了求助

### ISSUE THREAD

**Issue by infinity-M** [orzogc/acfunlive#30]
运行环境和编译环境皆已安装，但在使用GNU make和GO编译时，总会报错网络问题？
go: github.com/Mrs4s/MiraiGo@v0.0.0-20210120152724-83f2eb02e6be: Get "https://proxy.golang.org/github.com/%21mrs4s/%21mirai%21go/@v/v0.0.0-20210120152724-83f2eb02e6be.mod": dial tcp 216.58.220.XXX(手动更改):443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
阿巴阿巴试了好久了

**Comment by infinity-M** [comment]
哦对系统Windows

**Comment by orzogc** [comment]
golang的网址被墙了，需要用go proxy：https://goproxy.cn/

**Comment by infinity-M** [comment]
好的谢谢巨巨我去试试，但是科学上网全局代理按理来说不应该被强墙啊（哭

**Comment by infinity-M** [comment]
哦的确是少了一个set，单独set CGO_ENABLED=0后 go build -tags tray -ldflags -H=windowsgui就可以了
谢谢巨巨！
