### ISSUE TITLE
关于docker镜像的编译

### ISSUE THREAD

**Issue by bitest** [orzogc/acfunlive#31]
使用docker hub自身的自动编译没有什么问题，但是因为我需要运行arm64平台的镜像，docker hub在没有指定的时候只有amd64的版本，所以我通过docker的文档搞了个使用github actions功能利用buildx编译其他架构的脚本：[这个](https://github.com/bitest/acfunlive/blob/arm64/.github/workflows/build-docker-cli.yml)，但是编译会在yarn generate的地方失败，我只好在Dockerfile里删掉了ui的部分才能成功。大佬能不能看看是什么原因。。。

**Comment by orzogc** [comment]
有错误信息吗？

**Comment by bitest** [comment]
Dockerfile的RUN拆开跑了一个。
https://github.com/bitest/acfunlive/runs/2253229521?check_suite_focus=true
~~~~
Dockerfile:12
--------------------
  10 |     RUN yarn config set registry "https://registry.npm.taobao.org/"
  11 |     RUN yarn install
  12 | >>> RUN yarn generate
  13 |     
  14 |     FROM golang:1-alpine AS go_build
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn generate]: exit code: 1
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn generate]: exit code: 1
~~~~

**Comment by bitest** [comment]
https://github.com/bitest/acfunlive/runs/2253289321?check_suite_focus=true
这个是没动任何东西的Dockerfile跑出来的

**Comment by bitest** [comment]
我好像明白了，我的脚本无法获取submodule里的文件
```
#30 0.722 error Couldn't find a package.json file in "/acfunlive-ui-src"
#30 0.722 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#30 ERROR: executor failed running [/bin/sh -c yarn generate]: exit code: 1
```

**Comment by bitest** [comment]
问题已解决。
[脚本](https://github.com/bitest/acfunlive/blob/arm64/.github/workflows/build-docker-cli.yml)里添加了
```
  -
    name: Pull submodules
    run: git submodule update --init
```
测试编译成功了

希望大佬能做个官方的Docker Image.
