### ISSUE TITLE
已经无法登录了，看这意思是密钥证书的事

### ISSUE THREAD

**Issue by WENGLINK** [orzogc/acfunlive#32]
[ERROR] 登陆AcFun帐号时出现错误，取消登陆：Login() error: 登陆AcFun帐号失败：login() error: doRequest() error: x509: certificate is valid for *.kwd.inkuai.com, kwd.inkuai.com, not sec-cdn.gifshow.com

**Comment by orzogc** [comment]
用 [0.5.1](https://github.com/orzogc/acfunlive/releases/tag/v0.5.1) 版本
