### ISSUE TITLE
最近出现这种提示，请问是正常的吗

### ISSUE THREAD

**Issue by thmmjklp** [orzogc/acfunlive#34]
版本是0.5.1，3台服务器centos和Ubuntu都有这种情况
未知的State Signal item.SignalType：CommonStateSignalLiveState
payload string:
payload base64:
CAEQAQ==
 [ERROR] Recovering from panic in doRequest(), the error is: timeout
 [ERROR] fetchLiveRoom() error: 请求 https://api-new.app.acfun.cn/rest/app/live/channel 时出错，错误为 timeout
![QQ截图20210423225116](https://user-images.githubusercontent.com/18211135/115889615-ac67f880-a486-11eb-94a9-0dc9ef016b73.png)

**Comment by orzogc** [comment]
正常，你可以自己编译最新代码减少 `CommonStateSignalLiveState` 这类信息

**Comment by thmmjklp** [comment]
> 正常，你可以自己编译最新代码减少 `CommonStateSignalLiveState` 这类信息

了解，谢谢
