### ISSUE TITLE
更到最新版一直提示这个错误

### ISSUE THREAD

**Issue by rinyama** [orzogc/acfunlive#36]
2021/07/11 00:08:59 [ERROR] fetchLiveRoom() error: cannot parse JSON: cannot parse number: unexpected char: "<"; unparsed tail: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML...hr/>Powered by Tengine</body>\r\n</html>\r\n"
![image](https://user-images.githubusercontent.com/20681873/125169389-7eb86300-e1dc-11eb-96db-7d2770664aa2.png)

**Comment by orzogc** [comment]
请用最新版本
