### ISSUE TITLE
录像出现音画不同步问题

### ISSUE THREAD

**Issue by jkchou** [orzogc/acfunlive#37]
观看直播时音画正常同步，回头看录像时发现音画不同步，错位严重，难以手动校准

**Comment by orzogc** [comment]
所有录像都是？

**Comment by jkchou** [comment]
之前是正常的，就那天录播出错了

**Comment by orzogc** [comment]
> > 所有录像都是？
> 
> 之前是正常的，就那天录播出错了

哪场直播？

**Comment by jkchou** [comment]
> > > 所有录像都是？
> > 
> > 
> > 之前是正常的，就那天录播出错了
> 
> 哪场直播？

https://www.aliyundrive.com/s/q2nDENFvjbZ
大概从20多秒开始，主播切完屏幕后开始出现问题

**Comment by orzogc** [comment]
http://alivod.a.yximgs.com/livedvr/flv2ts/livecloud/kszt_CI10KdQMuNk.0-0.0-16.m3u8?auth_key=1628822599-798079129-0-202170245fb3ce95eed0f0bfbe8214a4
你看看官方录播有没有这个问题

**Comment by jkchou** [comment]
> http://alivod.a.yximgs.com/livedvr/flv2ts/livecloud/kszt_CI10KdQMuNk.0-0.0-16.m3u8?auth_key=1628822599-798079129-0-202170245fb3ce95eed0f0bfbe8214a4
> 你看看官方录播有没有这个问题
> 前面是有一段音画不同步

官方的没有问题，后面都对的上，我自己录的后面都对不上

**Comment by jkchou** [comment]
靠 刚才录的又对不上了，也是魔法少女蕉的直播，但别人的直播录像是正常的

**Comment by orzogc** [comment]
> 靠 刚才录的又对不上了，也是魔法少女蕉的直播，但别人的直播录像是正常的

直播源换成hls试试

**Comment by jkchou** [comment]
> 直播源换成hls试试

用的就是hls

**Comment by orzogc** [comment]
> > 直播源换成hls试试
> 
> 用的就是hls

那换成flv试试

**Comment by jkchou** [comment]
再请问一下，官方录像的链接怎么获得啊

**Comment by jkchou** [comment]
好了
