### ISSUE TITLE
最新版本QQbot有时不发消息

### ISSUE THREAD

**Issue by Kyokorin0** [orzogc/acfunlive#39]
win10下命令行运行，log显示给QQ发送消息成功，但是QQ并没有收到也没有消息记录，偶尔出现，难以复现

**Comment by orzogc** [comment]
你用的是0.5.7版本吗？

**Comment by Kyokorin0** [comment]
> 

是的。刚刚发现没有成功发送的消息，delconfig后再重新addnotifyon后发出的消息仍然不能收到

**Comment by orzogc** [comment]
程序运行的时间有多长？

**Comment by Kyokorin0** [comment]
我不太清楚是否是我的botQQ问题，因为我现在没有其他qq可以登录mirai，是否能复现凛琴（20806699）的问题？

**Comment by orzogc** [comment]
你的QQ帐号可能是被腾讯风控了

**Comment by Kyokorin0** [comment]
可是只有这一条消息不能发出，其他的都可以

**Comment by orzogc** [comment]
说明发的消息里面有敏感字

**Comment by Kyokorin0** [comment]
太奇怪了，按照消息格式，目标消息为
凛琴Rinkin（20806699）正在直播：艾欧白金单双排，直播观看地址：https://live.acfun.cn/live/20806699
同一botQQ号，通过电脑QQ手动发送可以正常收到

**Comment by orzogc** [comment]
确认是括号`（）`导致的，不清楚是MiraiGo的问题还是腾讯的问题

**Comment by orzogc** [comment]
请用0.5.8版本
