### ISSUE TITLE
录制直播时同时获取弹幕

### ISSUE THREAD

**Issue by Sokwva** [orzogc/acfunlive#4]
是否可以考虑以后加入 录制直播时将弹幕文件写入呢 
代码可以参考一下此项目：https://github.com/wpscott/AcFunDanmaku

**Comment by orzogc** [comment]
在做了，弹幕库的代码也差不多写好了，只不过还没有上传到github

**Comment by Sokwva** [comment]
刚刚看了一眼那个项目的star，发现大佬早就关注了啊。请问有什么办法能快点联系您呢？

**Comment by orzogc** [comment]
有什么你就在github说就是了

**Comment by orzogc** [comment]
弹幕库已上传
https://github.com/orzogc/acfundanmu

**Comment by Sokwva** [comment]
收到，大佬加油

**Comment by Sokwva** [comment]
收到，大佬加油

**Comment by orzogc** [comment]
现在可以下载弹幕了

**Comment by Sokwva** [comment]
请问一下，弹幕录制的存放位置是在程序运行的位置还是程序所在的位置呢

**Comment by orzogc** [comment]
程序所在的位置，log会提示

**Comment by Sokwva** [comment]
> 程序所在的位置，log会提示

没有相关的内容

**Comment by orzogc** [comment]
> > 程序所在的位置，log会提示
> 
> 没有相关的内容

下载时会提示，所有下载都默认存放在程序所在的位置

**Comment by hlytime** [comment]
发现一个问题，只下载弹幕会下载中断，不知道是不是弹幕不够密集

**Comment by orzogc** [comment]
> 发现一个问题，只下载弹幕会下载中断，不知道是不是弹幕不够密集

弹幕不够密集不会影响弹幕下载
你确定主播没有下播？有时候主播会下播后迅速上播

**Comment by hlytime** [comment]
没有下播，我全程在看，看log显示几分钟就结束了。刚才在Q老师的直播间试了试，因为人比较多，暂时没有异常，等一下我再找一个直播间测测，环境是腾讯云服务器

**Comment by orzogc** [comment]
> 没有下播，我全程在看，看log显示几分钟就结束了。刚才在Q老师的直播间试了试，因为人比较多，暂时没有异常，等一下我再找一个直播间测测，环境是腾讯云服务器

这个我遇到过，挺罕见的，你再遇到请另开一个issue
