### ISSUE TITLE
录播文件输出格式问题

### ISSUE THREAD

**Issue by RTSHSDFG** [orzogc/acfunlive#40]
使用的是 win gui 版本，默认输出 mp4 格式的文件，不清楚其他版本有没有这个问题。
当软件因为意外情况卡死或者退出的时候，会造成 mp4 格式下保存的录播文件损坏，从而无法正常打开播放。
修改输出格式为 flv 或 mkv 之后，再遇到同样的意外情况，此时保存的录播文件并没有损坏可以正常打开播放。
因为会有损坏录播文件的风险，感觉把 mp4 作为默认输出格式不是太合适。

**Comment by orzogc** [comment]
mp4的损坏是可以用工具修复的，比如[untrunc](https://github.com/anthwlock/untrunc)
