### ISSUE TITLE
开播提醒功能

### ISSUE THREAD

**Issue by infinity-M** [orzogc/acfunlive#45]
佬，将QQ群加入开播提醒列表后，会同步所有需要提醒的消息发入该群并at全体成员。

如下载视频发生错误、下载弹幕发生错误、如需重启，请输入xxxxx等。

会增加过多无意义 @全体成员 内容
期望更改为仅将开播/下播发进粉丝群，或处开播/下播外不@全体成员，或可选择是否at全体成员

十分感谢

**Comment by orzogc** [comment]
现在群通知只有开下播消息
