### ISSUE TITLE
新版本安装报错

### ISSUE THREAD

**Issue by infinity-M** [orzogc/acfunlive#46]
佬，环境Windows，卸载了老版本准备安装新版本，但无论是使用gnu make或 go build 都会报错

net/netip: package net/netip is not in GOROOT (C:\xxxxx\Go\src\net\netip)

检查后发现net目录中确实没有netip该文件，存在net.go文件
尝试重新安装更新版本的Go，版本1.17.9，仍存在该问题

十分抱歉打扰您

**Comment by orzogc** [comment]
至少需要go 1.18版本编译

**Comment by infinity-M** [comment]
收到！感谢！
