### ISSUE TITLE
构建Docker的时候会报错

### ISSUE THREAD

**Issue by Gleeeeeman** [orzogc/acfunlive#47]
![64bf9fcf2e3736bd1465c57a821dee2](https://user-images.githubusercontent.com/50981718/169851431-9ee3237c-2968-40e9-a2af-74a0c803983d.png)

好像是nodejs新版本的问题，在Dockerfile的10到11行中间插入

`export NODE_OPTIONS=--openssl-legacy-provider && \ `

命令之后可解决。

**Comment by orzogc** [comment]
这个应该解决了
