### ISSUE TITLE
标题里包含换行符导致的bug

### ISSUE THREAD

**Issue by Kyokorin0** [orzogc/acfunlive#49]
2022/06/19 16:17:15 [WARN] 因意外结束下载龙族少女（1761427）的直播弹幕，尝试重启下载
2022/06/19 16:17:15 Recovering from panic in WriteASS(), the error is: open C:\Users\Administrator\Desktop\client\2022-06-19 16-16-37 龙族少女
【百游联盟】~玩游戏转移 注意力.ass: The filename, directory name, or volume label syntax is incorrect.

**Comment by orzogc** [comment]
应该修复了
