### ISSUE TITLE
有没有人也一样无法在VPS使用

### ISSUE THREAD

**Issue by nil-ca** [orzogc/acfunlive#53]
> 2 00:01:33 如果要临时下载AC�ﱾ��的直播视频，可以运行 startrecord 23682490 或 startrecdan 23682490
2022/08/12 00:01:33 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 NewAcFunLive() error: 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 NewAcFunLive() error: 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 NewAcFunLive() error: 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 NewAcFunLive() error: 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}
2022/08/12 00:01:33 初始化失败：getToken() error: getLiveToken() error: 获取直播详细信息失败，响应为 {"errorCode":2,"status":"BLOCK"}

用acfun-tools输出日志为空白，不输出任何东西。
想看一下其他人是不是也是用VPS无法正常使用，最开始是用国外的VPS这样，现在换成腾讯云也变成这样了。

**Comment by orzogc** [comment]
服务器的IP地址被A站屏蔽了，换个IP地址或者等待几天看看会不会解封
