### ISSUE TITLE
增加对酷Q的支持

### ISSUE THREAD

**Issue by orzogc** [orzogc/acfunlive#6]
增加对酷Q的支持，从而做到QQ群的直播通知
相关库：
https://github.com/richardchien/coolq-http-api
https://github.com/catsworld/qq-bot-api

**Comment by Sokwva** [comment]
也可以考虑一下telegram的支持（虽然我自己都不怎么用，这个功能优先级可以靠后一点 ｂ(￣▽￣)

**Comment by hlytime** [comment]
设置好酷Q和CQHTTP插件和配置文件，命令行却没有相关命令，无法使用通知

**Comment by orzogc** [comment]
> 设置好酷Q和CQHTTP插件和配置文件，命令行却没有相关命令，无法使用通知

要编译最新的代码

**Comment by hlytime** [comment]
> > 设置好酷Q和CQHTTP插件和配置文件，命令行却没有相关命令，无法使用通知
> 
> 要编译最新的代码
> 今天应该会发布新版本，你可以用发布后的版本

谢谢，发布后我再试试，非常感谢！
