### ISSUE TITLE
增加对邮箱的支持

### ISSUE THREAD

**Issue by orzogc** [orzogc/acfunlive#8]
比如往微信或QQ绑定的邮箱发送开播提醒邮件，这样手机就能实时接受到开播提醒

**Comment by btjoker** [comment]
微信那个可以用 server酱
acfun现在推送也算及时, 没啥必要吧.

**Comment by orzogc** [comment]
> 微信那个可以用 server酱
> acfun现在推送也算及时, 没啥必要吧.

这个好

**Comment by Sokwva** [comment]
> 微信那个可以用 server酱
> acfun现在推送也算及时, 没啥必要吧.

确实，其实app现在是已经接入手机厂商的推送平台的；这个邮箱可以稍微慢点儿做
